-- Run this entire file in your Supabase project's SQL Editor.
-- Re-running it preserves existing guestbook entries.
begin;

create table if not exists public.guestbook_entries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 30 and name ~ '[^[:space:]]'),
  message text not null check (char_length(message) between 1 and 500 and message ~ '[^[:space:]]'),
  created_at timestamptz not null default now()
);

create index if not exists guestbook_entries_newest_idx
  on public.guestbook_entries (created_at desc, id desc);

alter table public.guestbook_entries enable row level security;

-- Public visitors can read and append only. Timestamps are generated by Postgres.
revoke all on table public.guestbook_entries from public, anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select on table public.guestbook_entries to anon, authenticated;
grant insert (id, name, message) on public.guestbook_entries to anon, authenticated;

drop policy if exists guestbook_public_read on public.guestbook_entries;
create policy guestbook_public_read on public.guestbook_entries
  for select to anon, authenticated using (true);

drop policy if exists guestbook_public_insert on public.guestbook_entries;
create policy guestbook_public_insert on public.guestbook_entries
  for insert to anon, authenticated with check (true);

-- INSERT notifications to every visitor viewing the guestbook.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'guestbook_entries'
  ) then
    alter publication supabase_realtime add table public.guestbook_entries;
  end if;
end $$;

commit;
